spring.application.name=Gym-Tracker

# JWT settings
jwt.secret=ChangeThisSecretKeyToAStrongRandomValueOfAtLeast32Bytes!
jwt.expiration-ms=3600000

# PostgreSQL datasource (dev)
spring.datasource.url=jdbc:postgresql://localhost:5432/gymtracker
spring.datasource.username=postgres
spring.datasource.password=1234

# We don't auto-run schema/data scripts in production-like setup
spring.sql.init.mode=never

# (Optional) If you keep schema management outside Spring (recommended: Flyway/Liquibase)
# spring.flyway.enabled=true

# PayPal Sandbox
paypal.client-id=AYG74FQxizmUtE3P7uYdsbKEUd6AvZ7o31mKd0voOto75HZV2adSrLpJETlc_rFK42SuCxMM_Oamwvy7
paypal.client-secret=EGjqoVpeUP64_HuxCqTkevdHJ9W4_noysngMgskZrRlOwIxP_w9a9DtrhwIb2PzlCt-t6dmda6S53YOM
paypal.base-url=https://api-m.sandbox.paypal.com
