-- Schema for embedded H2 database: users table used by AppUser entity
-- Spring Data JDBC quotes identifiers ("users"."ID"...), so we create uppercase column names.
CREATE TABLE IF NOT EXISTS users (
  ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  USERNAME VARCHAR(100) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  ROLES VARCHAR(255) NOT NULL
);
