-- Create tables with quoted lowercase identifiers to match Spring Data JDBC mappings
CREATE TABLE IF NOT EXISTS "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" VARCHAR(100) NOT NULL UNIQUE,
  "password" VARCHAR(255) NOT NULL,
  "roles" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "members" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT NOT NULL UNIQUE,
  "first_name" VARCHAR(80) NOT NULL,
  "last_name" VARCHAR(80) NOT NULL,
  "phone" VARCHAR(30),
  "birth_date" DATE,
  "active" BOOLEAN DEFAULT TRUE,
  CONSTRAINT fk_members_user FOREIGN KEY ("user_id") REFERENCES "users"("id")
);

CREATE TABLE IF NOT EXISTS "subscription_plans" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(100) NOT NULL,
  "duration_days" INT NOT NULL,
  "price_cents" INT NOT NULL,
  "includes_classes" BOOLEAN DEFAULT FALSE,
  "description" VARCHAR(1000),
  "active" BOOLEAN DEFAULT TRUE
);
